export const SET_LANGUAGE = 'APP/SET_LANGUAGE';
export const SET_DATA = 'APP/SET_DATA';
export const SET_PRODUCTS = 'APP/SET_PRODUCTS';
export const SET_REGIONS = 'APP/SET_REGIONS';
export const SET_ACTIVE_PRODUCT = 'APP/SET_ACTIVE_PRODUCT';
export const SET_CURRENT_REGION = 'APP/SET_CURRENT_REGION';
export const SET_CURRENT_CITY = 'APP/SET_CURRENT_CITY';
